language: java
dist: trusty
sudo: false

before_install:
  - mvn -N io.takari:maven:wrapper -Dmaven=3.6.3
  - echo "MAVEN_OPTS='-Dmaven.repo.local=$HOME/.m2/repository -Xmx1g'" > ~/.mavenrc

install:
  -

jobs:
  fast_finish: true
  include:
    - jdk: oraclejdk8
      env:
        - DESC="acceptance tests"
        - CMD="./mvnw install --projects acceptance-tests --also-make --activate-profiles all --no-transfer-progress"

    - jdk: oraclejdk8
      env:		
        - DESC="unit tests"		
        - CMD="./mvnw install"

    - jdk: oraclejdk11
      env:
        - DESC="unit tests oraclejdk11"
        - CMD="./mvnw install --no-transfer-progress"

    - jdk: oraclejdk14
      env:
        - DESC="unit tests oraclejdk14"
        - CMD="./mvnw install --no-transfer-progress"

    - jdk: oraclejdk8
      env:
        - DESC="unit tests Java15-EA"
        - JDK=Java15-EA
        - CMD="./.travis-command-ea-builds.sh"

  allow_failures:
    - jdk: oraclejdk8
      env:
        - DESC="unit tests Java15-EA"
        - JDK=Java15-EA
        - CMD="./.travis-command-ea-builds.sh"

script: eval travis_wait 30 $CMD

before_cache:
  - rm -rf $HOME/.m2/repository/org/eclipse/collections/

cache:
  directories:
    - $HOME/.m2
