language: java
dist: trusty
sudo: false

before_install:
  - mvn -N io.takari:maven:wrapper -Dmaven=3.6.1
  - echo "MAVEN_OPTS='-Dmaven.repo.local=$HOME/.m2/repository -Xmx1g -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss:SSS'" > ~/.mavenrc

install:
  -

jobs:
  fast_finish: true
  include:
    - jdk: oraclejdk8
      env:
        - DESC="acceptance tests"
        - CMD="./mvnw install --projects acceptance-tests --also-make --activate-profiles all"

    - jdk: oraclejdk8
      env:
        - DESC="findbugs"
        - CMD="./mvnw install findbugs:check --projects '!scala-unit-tests,!jmh-scala-tests,!jmh-tests,!jcstress-tests,!p2-repository' --activate-profiles all -DskipTests=true"

    - jdk: oraclejdk8
      env:
        - DESC="checkstyle"
        - CMD="./mvnw install checkstyle:check --activate-profiles all -DskipTests=true"

    - jdk: oraclejdk8
      env:
        - DESC="unit tests"
        - CMD="./mvnw install"

    - jdk: oraclejdk8
      env:
        - DESC="compile performance-tests"
        - CMD="./mvnw install --projects performance-tests --also-make --activate-profiles all -DskipTests=true"

    - jdk: oraclejdk8
      env:
        - DESC="compile javadoc"
        - CMD="./mvnw install javadoc:jar --projects '!unit-tests,!junit-trait-runner,!unit-tests-java8,!serialization-tests,!scala-unit-tests,!jmh-scala-tests,!jmh-tests,!jcstress-tests,!p2-repository,!test-coverage' --activate-profiles all -DskipTests=true"

    - jdk: oraclejdk9
      env:
        - DESC="unit tests oraclejdk9"
        - CMD="./mvnw install"

    - jdk: openjdk10
      env:
        - DESC="unit tests openjdk10"
        - CMD="./mvnw install"

    - jdk: openjdk11
      env:
        - DESC="unit tests openjdk11"
        - CMD="./mvnw install"

    - jdk: oraclejdk11
      env:
        - DESC="unit tests oraclejdk11"
        - CMD="./mvnw install"

    - jdk: openjdk12
      env:
        - DESC="unit tests openjdk12"
        - CMD="./mvnw install"

    - jdk: openjdk-ea
      env:
        - DESC="unit tests openjdk-ea"
        - CMD="./mvnw install"

    - jdk: oraclejdk8
      env:
        - DESC="unit tests Java12-EA"
        - JDK=Java12-EA
        - CMD="./.travis-command-ea-builds.sh"

  allow_failures:
    - jdk: openjdk-ea
      env:
        - DESC="unit tests openjdk-ea"
        - CMD="./mvnw install"
    - jdk: oraclejdk8
      env:
        - DESC="unit tests Java12-EA"
        - JDK=Java12-EA
        - CMD="./.travis-command-ea-builds.sh"

script: eval travis_wait 30 $CMD

before_cache:
  - rm -rf $HOME/.m2/repository/org/eclipse/collections/

cache:
  directories:
    - $HOME/.m2
