language: java
sudo: false

before_install: echo "MAVEN_OPTS='-Dmaven.repo.local=$HOME/.m2/repository -Xmx1g -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss:SSS'" > ~/.mavenrc
install:
  -

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
      env:
        - DESC="acceptance tests"
        - CMD="mvn install --projects acceptance-tests --also-make --activate-profiles all --batch-mode --show-version --errors"

    - jdk: oraclejdk8
      env:
        - DESC="findbugs"
        - CMD="mvn install findbugs:check --projects '!scala-unit-tests,!jmh-scala-tests,!jmh-tests' --activate-profiles all -DskipTests=true --batch-mode --show-version --errors"

    - jdk: oraclejdk8
      env:
        - DESC="checkstyle"
        - CMD="mvn install checkstyle:check --activate-profiles all -DskipTests=true --batch-mode --show-version --errors"

    - jdk: oraclejdk8
      env:
        - DESC="unit tests"
        - CMD="mvn install --batch-mode --show-version --errors"
        - SONAR_COMMAND="sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=${SONARQUBE_TOKEN} -Dsonar.organization=eclipse-collections"

    - jdk: oraclejdk8
      env:
        - DESC="compile jmh-tests and performance-tests"
        - CMD="mvn install --projects jmh-tests,performance-tests --also-make --activate-profiles all -DskipTests=true --batch-mode --show-version --errors"

script:
  if ["$TRAVIS_EVENT_TYPE" == "cron"]; then
      eval travis_wait 35 $CMD $SONAR_COMMAND;
  else
      eval travis_wait 35 $CMD;
  fi

cache:
  directories:
  - ~/.m2
