# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Checkstyle

on: [push, pull_request]

jobs:
  applications:
    name: Checkstyle ${{ matrix.java-version }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [11]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Set Maven Wrapper
        run: mvn -N io.takari:maven:0.7.7:wrapper -Dmaven=3.6.3
      - name: Set JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
      - name: Checkstyle
        run: ./mvnw install checkstyle:check --activate-profiles all -DskipTests=true --no-transfer-progress
        env:
          MAVEN_OPTS: "-Xmx1g"

