# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Unit tests

on: [push, pull_request]

jobs:
  applications:
    name: Unit Test ${{ matrix.java-version }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [8, 11, 14]

    runs-on: ${{ matrix.os }}

    env:
      JAVA_VERSION: ${{ matrix.java-version }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Set Maven Wrapper
        run: mvn -N io.takari:maven:0.7.7:wrapper -Dmaven=3.6.3
      - name: Set JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
      - name: Unit-Test
        run: ./mvnw verify --no-transfer-progress
        env:
          MAVEN_OPTS: "-Xmx1g"

